version: "3.1"
services:
  elk:
    container_name: elk_service
    build:
      context: ./elk/
    ports:
      - "5601:5601"
      - "5044:5044"
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    networks:
      - es_net

  api:
    container_name: elk_api
    build:
      context: ./api/
    ports:
      - "420:420"
    networks:
      - es_net

networks:
  es_net:
    name: es_net
    driver: default