version: "3.1"
services:
  elk:
    container_name: elk_service
    build:
      context: ./elk/
    env_file: 
      - .env
    volumes:
      - elk-service-data:/var/lib/elasticsearch
      - elk-service-csv:/data/elasticsearch/load
    ports:
      - 5601:5601
      - 5044:5044
      - 9200:9200
      - 9300:9300
      - 9600:9600
    networks:
      - es_net

  gpt3:
    container_name: elk_gpt3
    depends_on:
      - elk
    build:
      context: ./gpt3-davinci/
    env_file:
      - .env
    volumes:
      - gpt-service-log:/opt/gpt3/api/log
    ports:
      - 4200:4200
    expose:
      - 5000
    networks:
      - es_net

  api:
    container_name: elk_api
    depends_on:
      - elk
    build:
      context: ./api/
    env_file: 
      - .env
    volumes:
      - elk-service-csv:/opt/api/data/csv/finished
    ports:
      - 420:420
    expose:
      - 5000
    networks:
      - es_net

volumes:
  elk-service-data:
  elk-service-csv:
  gpt3-service-log:

networks:
  es_net:
    driver: bridge
