version: "3"
services:
  elk:
    container_name: elk_service
    build:
      context: ./elk/
    network_mode: host
    env_file:
      - .env
    volumes:
      - elk-service-data:/var/lib/elasticsearch
      - elk-service-csv:/data/elasticsearch/load
    ports:
      - 5601:5601
      - 5044:5044
      - 9200:9200
      - 9300:9300
      - 9600:9600

  gpt3:
    container_name: elk_gpt3
    depends_on:
      - elk
    network_mode: host
    build:
      context: ./gpt3-davinci/
    env_file:
      - .env
    volumes:
      - gpt-service-log:/opt/gpt3/api/log
      - gpt-service-hist:/opt/gpt3/api/history/saved
    ports:
      - 4200:4200
    expose:
      - 5000

  api:
    container_name: elk_api
    depends_on:
      - elk
    network_mode: host
    build:
      context: ./api/
    env_file:
      - .env
    volumes:
      - elk-service-csv:/opt/api/data/csv/finished
      - elk-api-log:/opt/api/log
    ports:
      - 420:420
    expose:
      - 5000

volumes:
  elk-service-data:
  elk-service-csv:
  elk-api-log:
  gpt-service-log:
  gpt-service-hist: