version: "3.1"
services:
  elk:
    container_name: elk_service
    build:
      context: ./elk/
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  api:
    container_name: elk_api
    build:
      context: ./api/
    ports:
      - "8888:8000"
